apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: NODE_ENV
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: PGDATABASE
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: PGPASSWORD
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: PGUSER
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: PORT
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-secrets
                  key: SESSION_SECRET
